version: '3.1'

services:
  mc_pg:
    image: postgres:15.1
    container_name: mc_pg
    restart: always
    environment:
      POSTGRES_DB: nestdb
      POSTGRES_USER: umc
      POSTGRES_PASSWORD: secret
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432